name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      uses: zyborg/dotnet-tests-report@v1.0.0
      with:
        report_name: unit_tests_<datetime>
        report_title: Unit Tests
        github_token: ${{ secrets.GITHUB_TOKEN }}
        set_check_status_from_test_outcome: true
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and Push to Docker Hub
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: 4lexkislitsyn/request-percolator
        tags: latest
        tag_with_ref: false
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
