on:
  workflow_dispatch:
    prerelease:
      description: 'Start prerelease'
      required: true
      default: true
    version:
      description: 'Release version without prerelease postfix'
      required: true
      default: '0.0.1'
    notes:
      required: false
      default: ''

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - id: vars
        run: |
          echo ::set-output name=sha_short::$(git rev-parse --short=4 ${{ github.sha }})
      - id: extract_branch
        run: |
          echo ::set-env name=branch_name::$(echo ${GITHUB_REF#refs/heads/})
      - name: Create Release
        id: create_release
        uses: juitnow/github-action-create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{github.event.inputs.version}}-alpha-${{ steps.vars.sha_short }}
          release_name: Prerelease from branch '${{ steps.extract_branch.branch_name }}'
          body: ${{github.event.inputs.notes}}
          draft: true
          prerelease: true
